version: "3.8"
services:
  mongodb:
    image: mongo:8.0.3
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/jobseeker-appr-test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=jobseeker-db
volumes:
  data: {}
networks:
  default:
    name: mongodb_network